"""googl  migration

Revision ID: 31568dc3ecc2
Revises: caf22cba52dd
Create Date: 2024-09-15 15:23:11.800030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31568dc3ecc2'
down_revision = 'caf22cba52dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
