"""prod migrations

Revision ID: 328b834f99cc
Revises: a9a1e0183834
Create Date: 2024-09-10 23:20:56.651462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328b834f99cc'
down_revision = 'a9a1e0183834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
