"""googl  migration

Revision ID: 35507e198cb0
Revises: abdb50992754
Create Date: 2024-09-15 16:36:58.717558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35507e198cb0'
down_revision = 'abdb50992754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
