"""prod migrations

Revision ID: 58486eed0be4
Revises: 328b834f99cc
Create Date: 2024-09-10 23:52:01.111919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58486eed0be4'
down_revision = '328b834f99cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
