"""add donations

Revision ID: 64941bb79211
Revises: c69ff9639b86
Create Date: 2024-09-08 20:50:51.639103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64941bb79211'
down_revision = 'c69ff9639b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
