"""role user

Revision ID: 804b169a7d80
Revises: a723679bdd75
Create Date: 2024-09-07 22:07:55.135165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804b169a7d80'
down_revision = 'a723679bdd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
