"""prod migrations

Revision ID: a9a1e0183834
Revises: bf51b400ca6f
Create Date: 2024-09-09 23:34:41.296573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a1e0183834'
down_revision = 'bf51b400ca6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
