"""googl  migration

Revision ID: abdb50992754
Revises: 31568dc3ecc2
Create Date: 2024-09-15 16:05:34.497162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdb50992754'
down_revision = '31568dc3ecc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
