"""add charity_project

Revision ID: c69ff9639b86
Revises: 804b169a7d80
Create Date: 2024-09-08 20:05:06.516469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69ff9639b86'
down_revision = '804b169a7d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
