"""after rew

Revision ID: caf22cba52dd
Revises: 58486eed0be4
Create Date: 2024-09-13 01:16:22.059968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf22cba52dd'
down_revision = '58486eed0be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
